browser_height = 2500
browser_width = 2500
excluded_titlecase_words = ["of", "and", "the", "to", "at", "for"]
driver_executable = ""
browser = "chrome"
client_id = ""
token_secret =""
leagues = ["Bestiary", "Bestiary Hardcore", "Hardcore", "Standard", "Flashback", "Flashback Hardcore"]
wiki = "https://pathofexile.gamepedia.com/{}"